{% set name = "openmoltools" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/openmoltools/archive/{{ version }}.tar.gz
  sha256: e808b8f8696ed42367e33c28b01f893783126212580e64472c810b970a610b1a
  patches:
    - setup.patch

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - six
    - mdtraj
    - numpy >=1.14
    - numpydoc
    - scipy
    - openmm
    - ambertools >=19
    - pytables

test:
  requires:
    - python {{ python_min }}
  imports:
    - openmoltools

about:
  home: https://github.com/choderalab/openmoltools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for Small Molecules, Antechamber, OpenMM, and more
  description: |
    This set of tools allows users to automate various tasks related to
    simulating small molecules using various molecules dynamics techniques.
    It also contains several python tools for working with small molecules,
    packing boxes (python wrappers for packmol), and parameterizing small molecules.
    It also contains tools for creating OpenMM XML forcefield files for small molecules,
    although we currently focus on the use of AMBER prmtop and inpcrd files due
    to their widespread use.
  doc_url: https://github.com/choderalab/openmoltools
  dev_url: https://github.com/choderalab/openmoltools

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
    - ijpulidos
